SELECT SPACES.SPACENAME, MAX(C.USER_NAME) AS "USER_NAME", MAX (C.DISPLAY_NAME) AS "DISPLAY_NAME", MAX(CONTENT.LASTMODDATE) AS "LASTMODDATE", MAX(SPACES.SPACESTATUS) AS "SPACESTATUS", MAX(SPACES.CREATIONDATE) AS "CREATIONDATE"
FROM CONTENT, SPACES JOIN SPACEPERMISSIONS P ON SPACES.SPACEID = P.SPACEID
JOIN user_mapping U ON SPACES.CREATOR = U.USER_KEY
JOIN cwd_user C ON U.USERNAME = C.USER_NAME
WHERE CONTENT.SPACEID = SPACES.SPACEID AND SPACES.SPACETYPE like 'global' AND SPACES.SPACESTATUS = 'CURRENT'
GROUP BY SPACES.SPACENAME ORDER BY SPACES.SPACENAME;